### ISSUE TITLE
authentication process fails

### ISSUE THREAD

**Issue by benoitpointet** [panalysis/Google2Pandas#13]
I placed the client-secrets.json file in the right place with correct permissions.

When I first call the API and go through the authentication process (select the account, give permissions to application to access my data), I then end up in new window calling `http://localhost:8080/?code=4/...` with an error no-data, meaning no answer from the server I suppose.

Any way to troubleshoot that?

**Comment by DeliciousHair** [comment]
Try placing the `client_secrets.json` and `analytics.dat` files in the directory you're running your query from and see if you still get the same problems.

Explicitly, if the `analytics.data` file does not yet exist, one will be created the first time you use instantiate the class--that's when you need to alter the permissions/ownership and move it to the default location if you want to.  So, let's assume you have obtained the `client_secrets.json` file and it's sitting in the same directory where you have started up python. Then you would do:

```
from google2pandas import *
conn = GoogleAnalyticsQuery(secrets='client_secrets.json', token_file_name='analytics.dat')
```

which will then get the authentication process going in a browser (at least I end up getting a browser, depends on your system configuration). Do that, then exit.

Adjust the ownership / permissions of the `analytics.dat` file:

```
chmod 664 analytics.dat    # of course, this was already done prior to the previous step
chmod 664 client_secrets.json

# maybe move both of these files if you're so inclined, then finally
chown <user or group>:<group> analytics.dat
```

Then try in python again:

```
from google2pandas import *
conn = GoogleAnalyticsQuery()
```

If that doesn't work, please post the full error message, sans anything about `ids` values.

**Comment by benoitpointet** [comment]
Thx!

Got this to work in a little py script: it finds. And uses the secrets file
and generates the analytics.dat. Yet when i use the same code in a jupyter
notebook it reauthenticates and fails in the browser window it opens.

## 

Liip FR +41 26 422 2511 http://liip.ch

**Comment by DeliciousHair** [comment]
Can you please post a minimal example?  Again, without any ids values.

**Comment by benoitpointet** [comment]
```
from google2pandas import *
conn = GoogleAnalyticsQuery(secrets='./ga-creds/client_secrets.json', token_file_name='./ga-creds/analytics.dat')

query = {\
    'ids'           : 'MY-VIEW-ID',
    'metrics'       : 'pageviews',
    'dimensions'    : ['date', 'pagePath', 'browser'],
#    'filters'       : ['pagePath=~iPhone', 'and', 'browser=~Firefox'],
    'start_date'    : '8daysAgo',
    'max_results'   : 10}

df, metadata = conn.execute_query(**query)
print(df)
```

I think it relates to the fact that the jupyter notebook kernel does not have the same user, group and thus privileges on those two files and potentially on creating a temporary webserver than my own user ...

**Comment by benoitpointet** [comment]
ah nah jupyter notebooks run with my user ...

**Comment by benoitpointet** [comment]
solved the thing. I had messed up the files perms. good thing your lib allows to specify client secrets file, that allows to access multiple accounts.

**Comment by DeliciousHair** [comment]
Yeah, I don't fully 'get' why the permissions on the `analytics.dat` file are so specific, but it is what it is, hence the inclusion of the keyword argument :-)

Glad to hear you got it sorted out!
