### ISSUE TITLE
dealing with more than 10000 rows

### ISSUE THREAD

**Issue by danailon** [panalysis/Google2Pandas#14]
Dear,

when querying GA with pagepath/pagetitle dimensions you easily get more than 10000 daily rows.

How to overcome this?

My best,
Danilo

**Comment by DeliciousHair** [comment]
You need to embed your query into some sort of loop that will advance the

**Comment by DeliciousHair** [comment]
You simply need to embed your query into a loop that will advance the `start_index` keyword along until you get all the data associated with your query, since GA only returns 10k rows maximum in a single query.

Oh, and thanks for using the module!
