### ISSUE TITLE
Query size changes during iteration (results in `RuntimeError`)

### ISSUE THREAD

**Issue by chadlagore** [panalysis/Google2Pandas#15]
Thanks for the great package :+1:

Sometimes I pass the same query into two separate query systems, `google2pandas` and maybe a database client of some sort, it might look like this:

``` python
DEVICE = 'mobile'

ARGS = {
    'start_date': '2016-07-27',
    'end_date': '2016-08-25',
    'filters': ['deviceCategory=~{}'.format(DEVICE)],
    'metrics': ['sessions', 'pageviews', 'users', 'transactions', 'transactionRevenue'],
    'dimensions': ['date'],
    'device': DEVICE,
    'samplingLevel': 'HIGHER_PRECISION'
}
```

Of course here, `google2pandas` might like to remove the `device` key.

If you pass an unrecognized query parameter into the `execute_query` method, `google2pandas` tries to `pop` it, using [this](https://github.com/panalysis/Google2Pandas/blob/master/google2pandas/_query_parser.py#L108) chunk of code:

``` python
 #7. Remove options that should not be there
        for key in query.keys():
            if key not in ['ids', 'start_date', 'end_date', 'metrics', \
                            'dimensions', 'sort', 'filters', 'segment', \
                            'samplingLevel', 'start_index', 'max_results', \
                            'output', 'fields', 'userIp', 'quotaUser']:
                query.pop(key)

                print('Removed invalid query parameter \'{0}\''.format(key))
```

You can see how this results in `RuntimeError: dictionary changed size during iteration.` I think this is one good way to go about it:

``` python
accept = ['ids', 'start_date', 'end_date', 'metrics', \
          'dimensions', 'sort', 'filters', 'segment', \
          'samplingLevel', 'start_index', 'max_results', \
          'output', 'fields', 'userIp', 'quotaUser']

for key, value in list(ARGS.items()):
    if key not in accept:
        del ARGS[key]
```

I'd love to put in a pull request :)

**Comment by DeliciousHair** [comment]
Hi there,

Glad you like the package, compliments always gladly accepted😃😃😃

By all means, please put in a pr! The problem with this package is the inability to do unit testing on it owing to it needing a ga account to operate on. I'm no longer at Panalysis (but am maintaining this module) so I cannot do any testing myself and will just need you to provide some sort of evidence of it working to commit the changes is all. 

Please email me to discuss, and I look forward to your pr soon.

**Comment by chadlagore** [comment]
Thanks for the quick response. I'll try to find a way to provide some unit tests with the PR. Talk to you shortly.

**Comment by DeliciousHair** [comment]
That would be great, but buy evidence I simply mean (in this instance) is that your fix doesn't break any of the `maybe_fix` methods. Ultimately all this module does is forms a json object to pass to ga and gets one back, not much to test fortunately 😃

**Comment by jaypeedevlin** [comment]
Just a thought, does the new GA demo account include API access?  Might be useful for the purpose: https://analytics.googleblog.com/2016/08/introducing-google-analytics-demo.html

Edit: Just found the FAQ, the answer is unfortunately no.

**Comment by DeliciousHair** [comment]
Did you get a pr together for this? I am now in a position to check and commit it, so would certainly welcome it.

Otherwise I may just close this off for the time being.

Cheers!
