### ISSUE TITLE
how to deal while behind a proxy

### ISSUE THREAD

**Issue by danailon** [panalysis/Google2Pandas#16]
Dear all,

I need to make GA api request but I'm behind a proxy.

Any suggestion?

My best,
Danilo

**Comment by DeliciousHair** [comment]
Hm, good question. I once again have access to GA so I'll have a play with this in the next few days if somebody else doesn't come up with something first.

**Comment by DeliciousHair** [comment]
I have no practical way of coming up with a solution to this problem as I would need to set up my own proxy server specifically for the purpose of getting through it, which I do not have the time nor technical skills to deal with at the moment.

Closing this issue for now owing to lack of interest in dealing with it, will be happy to re-open if anyone has a solution to offer.
