### ISSUE TITLE
explicit scope in filters is broken

### ISSUE THREAD

**Issue by yuvalqen** [panalysis/Google2Pandas#17]
Hi guys,

Amazing plugin, I really like it.

I ran into the following issue:
GA API supports explicit definition of scope as seen [here](https://developers.google.com/analytics/devguides/reporting/core/v3/segments).

The syntax for the scopes does not start with "ga:". For example:
`sessions::condition::ga:browser==Chrome`

Google2Pandas enforces a "ga:" at the beginning of each filter element which breaks this functionality of GA API.

Can you advise a workaround?

I might send a pull request when I have some time to look into the code.

Thanks!

**Comment by DeliciousHair** [comment]
I'm not sure I'm following your question; isn't this dealt with directly in `segment` already?  From `QueryParser.parse()`:

```
    # 7. Remove options that should not be there
    for key in query.keys():
        if key not in ['ids', 'start_date', 'end_date', 'metrics', \
                        'dimensions', 'sort', 'filters', 'segment', \
                        'samplingLevel', 'start_index', 'max_results', \
                        'output', 'fields', 'userIp', 'quotaUser']:
            query.pop(key)

            print('Removed invalid query parameter \'{0}\''.format(key))

    # Nothing to do for 'segment' actually as it's too fleixible to
    # fix into this fix-via-intuition framework, at least I'm not seeing
    # anything obvious. For now, the user has to get it correct.
```

In other words, you have go specify segments in a contextually correct manner at the user-level already (ie, including the `ga:` prefix) as the parser doesn't touch them.

Or am I misunderstanding your question (which is entirely possible...)

**Comment by yuvalqen** [comment]
My bad! I just mixed up two different GA API features namely filters and segments.
