### ISSUE TITLE
dimensions is documented as optional yet code raises KeyError on missing dimensions

### ISSUE THREAD

**Issue by yuvalqen** [panalysis/Google2Pandas#18]
Hi,

I ran a query with the following parameters:
{'metrics': 'sessions', 'samplingLevel': 'HIGHER_PRECISION', 'max_results': '10000', 'start_date': '7daysAgo', 'ids': '1234567890'}

I get a KeyError exception on line 60 of _query_parser:
`lst = query['ids'], query['dimensions'], query['metrics']`

According to GA API dimensions isn't required.

**Comment by yuvalqen** [comment]
A workaround is to provide it an empty list BTW.

**Comment by DeliciousHair** [comment]
Good catch!

I'll try to fix that a little later today, or feel free to submit pr of your own😃
