### ISSUE TITLE
It's not an actual issue but just want to know how to know whether response data is sampled or not and also some other parameters mentioned below

### ISSUE THREAD

**Issue by smanikandan7** [panalysis/Google2Pandas#30]
Hi All , I am successfully able to connect to GA and retrieve data, but want to know whether the response data is sampled or not . I am not able to get this field from output dataframe

Also, I tried in query explorer and seems we have big dataset even in a single day, so how to query for each hour in a day, retrieve the data and merge it. 

Pls help !!

**Comment by PanalysisLeo** [comment]
Hi smanikandan7,

Here is an example of how to detect sampling in a Google2Pandas query:

```
query = {\
        'ids'           : profile_id,
        'metrics'       : metrics,
        'dimensions'    : ['ga:date'],
        'sort'          : 'ga:date',
        'start_date'    : start,
        'end_date'      : end,
        'max_results'   : 10000}

df, metadata = ga.execute_query(**query)

if (metadata['containsSampledData']):
            print 'Sampling'
```

As for retrieving data hourly, here is a very general example of appending successive queries to an empty dataframe:

```
query = {\
        'ids'           : profile_id,
        'metrics'       : metrics,
        'dimensions'    : ['ga:day'],
        'sort'          : 'ga:hour',
        'start_date'    : start,
        'end_date'      : end,
        'max_results'   : 1}

all_results = pd.DataFrame() # Empty dataframe

for i in range(0, 24):
    
    if (i < 10):
        query['filters'] = 'ga:hour==0%s' % str(i)
    else:
        query['filters'] = 'ga:hour==%s' % str(i)
        
    df, metadata = ga.execute_query(**query)
    
    all_results = all_results.append(df, ignore_index=True)
    
```

Thanks,
Leo

**Comment by DeliciousHair** [comment]
Closing this as it's not an issue, but do feel free to discuss :-)

**Comment by smanikandan7** [comment]
Thanks for the above solutions but can i know how to make it work in v4 API.

**Comment by smanikandan7** [comment]
Hi DeliciousHair,

Can you please help on how to do it in V4 request ??

**Comment by DeliciousHair** [comment]
Heyo!

Check out the example on the README, it should get you started. More generally though, [google has done a pretty good job of documenting the API](https://developers.google.com/analytics/devguides/reporting/core/v4/).

Good luck!
