### ISSUE TITLE
Pypi release ?

### ISSUE THREAD

**Issue by bharling** [panalysis/Google2Pandas#32]
Hi,

Wonderful library - thankyou! Vastly simplifies reporting for our project. Just wondered if a pypi release is in the works? I'd rather have a tagged release in our project requirements than a link to the github master

thanks :)

**Comment by DeliciousHair** [comment]
Heyo!

I had meant to get around to that, but didn't because... lazy I guess? Lemme check a few things and just do that :-)

**Comment by DeliciousHair** [comment]
Done!  `pip install Google2Pandas` works as expected.

**Comment by bharling** [comment]
cool, thanks
