### ISSUE TITLE
GoogleMCFQuery - Can't query with dimensions

### ISSUE THREAD

**Issue by PanalysisLeo** [panalysis/Google2Pandas#39]
Hi,

I found a bug which prevents MCF queries which contain dimensions.
Line 432 of _panalysis_ga needs the number changed from 3 to 4:
![image](https://user-images.githubusercontent.com/19424152/33536170-f6f55f2c-d906-11e7-9be6-81bba12d5101.png)
The 3 is presumably left from copy-pasting the core API class, but "mcf:" is 4 characters, so the program will crash when trying to build/format the DataFrame.

Thanks,
Leo

**Comment by DeliciousHair** [comment]
As accurately pointed out by @QuinRiva in #40, this should not have been hard-coded into the method in the first place anyway, and has now been fixed in #40 as well.
