### ISSUE TITLE
Unicode bug

### ISSUE THREAD

**Issue by azu-p** [panalysis/Google2Pandas#4]
The lines are:

```
        def my_mapper(x):
            if x == u'INTEGER':
                return int
            elif x == u'BOOLEAN':
                return bool
            else:
                return str

        for hdr in res[u'columnHeaders']:
            col = hdr[u'name'][3:]
            dtp = hdr[u'dataType']

            df[col] = df[col].apply(my_mapper(dtp))
```

The error is:

Traceback (most recent call last):
File "dataExtractor2.py", line 83, in <module>
temp, qry = g2p.execute_query(**query)
File "C:\Python27\lib\site-packages\google2pandas_panalysis_ga.py", line 230,
in execute_query
df[col] = df[col].apply(my_mapper(dtp))
File "C:\Python27\lib\site-packages\pandas\core\series.py", line 2169, in appl
y
mapped = lib.map_infer(values, f, convert=convert_dtype)
File "pandas\src\inference.pyx", line 1059, in pandas.lib.map_infer (pandas\li
b.c:62578)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2006' in position 1
: ordinal not in range(128)

It looks like the issue can be fixed with the Unicode functions at https://docs.python.org/2/howto/unicode.html#the-unicode-type

Not sure if the code works with Python 3 or greater and I would like to add this to the queue as well.

The query that raises it is:
 query = {'metrics': 
 ['pageviews', 'uniquePageviews'], 
 'max_results': 10000, 
 'dimensions'
: ['date', 'dimension1'], 
'end_date': '2015-06-30', 
'ids': 'XXXX', 
'start_index': 1, 
'start_date': '2015-06-01'}

Thanks

Rod

**Comment by DeliciousHair** [comment]
fixed with #5
